name: "benchmarks"

on: workflow_dispatch

jobs:
  unit-tests:
    name: "benchmarks"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.0"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json, opcache, apcu
          coverage: none

      - name: "installing dependencies"
        run: "composer install --no-interaction --no-progress --prefer-dist --no-dev --classmap-authoritative"

      - name: "running first case"
        run: php vendor/bin/phpbench run
      - name: "running benchmark"
        run: php vendor/bin/phpbench run --report=default --output=html
      - name: "create result.md"
        run: php scripts/html-to-markdown.php
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update benchmark
